[connections.default]
account = "https://zffdage-ecb47142.snowflakecomputing.com"
user = "keppro"
password = "tbhwGDqc@2y*YfyoQa5qH"
warehouse = "QUICKSTART_WH"
database = "QUICKSTART_COMMON"
schema = "PUBLIC"
role = "ACCOUNTADMIN"